framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    disallow_search_engine_index: false

    session:
        handler_id: null
        storage_factory_id: session.storage.factory.native # ✅ Correct
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    assets:
        packages:
            uploads:
                base_path: '%kernel.project_dir%/public/uploads'
