nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    csp:
        hosts: []
        content_types: []
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src:
                - 'self'    
                - 'https://foryoumer.com/assets/fonts/'
            img-src:
                - 'self'
                - https://foryoumer.com/uploads/
                - https://foryoumer.com/assets/images/
                - https://*.stripe.com
    
            connect-src:
                - 'https://foryoumer.com/'
                - 'https://checkout.stripe.com'
                - 'https://api.stripe.com'
                - 'https://js.stripe.com/v3/'
                
                

            font-src: ['https://foryoumer.com/']    
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://code.jquery.com'
                - 'https://cdnjs.cloudflare.com'
                - 'https://cdn.jsdelivr.net'
                - 'https://foryoumer.com'
                - 'https://js.stripe.com/v3/'
                
            frame-src:
                - 'https://js.stripe.com/'    
                
            style-src: ["'self'", "'unsafe-inline'", "https://foryoumer.com/assets/css/style.css", "https://foryoumer.com/assets/css/custom_bootstrap.css", "https://foryoumer.com/assets/css/normalize.css", "https://foryoumer.com/assets/css/fontawesome.css", "https://foryoumer.com/assets/css/elegant.css", "https://foryoumer.com/assets/css/animate.css", "https://foryoumer.com/assets/css/slick.css", "https://foryoumer.com/assets/css/scroll.css", "https://foryoumer.com/assets/css/icomoon.css", "https://foryoumer.com/assets/css/jquery.fancybox.min.css", "https://foryoumer.com/assets/css/mystore.css", "https://foryoumer.com/assets/css/select2.min.css", "https://foryoumer.com/build/css/intlTelInput.css"]
            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
            # upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport

   

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
