# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.upload_directory: '%kernel.project_dir%/public/uploads'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Twig\AppExtension:
        tags: ["twig.extension"]

    App\Service\FileUploader:
        arguments:
            - '%app.upload_directory%' 
    App\EventListener\RemoveXRobotsTagSubscriber:
        tags:
            - { name: kernel.event_subscriber }           

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
            - "../src/Tests/"

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "../src/Controller/"
        tags: ["controller.service_arguments"]

    fos_elastica.index.products.product:
        class: FOS\ElasticaBundle\Elastica\Index
        factory: ['@fos_elastica.client', getIndex]
        arguments:
            - 'products'
            
    app.elastica_to_model_transformer:
        class: FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer
        arguments:
            - '@doctrine'
            - 'App\Entity\Product'
            - [] # options (vous pouvez laisser vide si vous n'avez pas besoin d'options spécifiques)        

    app.product_finder:
        class: FOS\ElasticaBundle\Finder\TransformedFinder
        arguments:
            - '@fos_elastica.index.products.product'
            - '@app.elastica_to_model_transformer'

    App\Service\ElasticsearchService:
        arguments:
            $client: '@fos_elastica.client.default'
            $productFinder: '@app.product_finder'

              

   
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
   

